### PR TITLE
Dim 1024: "Heschl’s gyrus LH" -> "Heschl’s gyrus middle LH'

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
https://parietal-inria.github.io/DiFuMo/1024/html/830.html
This is a subpart of Heschl's gyrus.

Other subparts: https://parietal-inria.github.io/DiFuMo/1024/html/416.html, https://parietal-inria.github.io/DiFuMo/1024/html/71.html

### CODE REVIEW

**Comment by antonia-ms** [comment]
Agreed.

**Comment by bthirion** [comment]
Note sure. The fact is that this regions is really "below", in terms of z coordinate
'Heschel's gyrus Ventral LH' ?

**Comment by GaelVaroquaux** [comment]
> Note sure. The fact is that this regions is really "below", in terms of z
> coordinate
> 'Heschel's gyrus Ventral LH' ?

Fine with me. Antonia?

**Comment by KamalakerDadi** [comment]
ping @antonia-ms

**Comment by antonia-ms** [comment]
Yes ventral makes sense. Let's call it 'inferior' instead for consistency 'Heschl's gyrus inferior LH'

**Comment by KamalakerDadi** [comment]
>Yes ventral makes sense. Let's call it 'inferior' instead for consistency 'Heschl's gyrus inferior LH'

Pushed the change directly on to your branch.

Ready to merge this one.

**Pull request merged**
